name: Build Release App Bundle

# Permite que rode manualmente
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      # Decodifica nosso keyStrore de Base64
      - name: Decode Keystore
        env:
            ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
            TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
            mkdir "${TMP_KEYSTORE_FILE_PATH}"
            echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/your_keystore_file.jks
